package edu.brown.cs32.examples.moshiExample.server.Handlers;

import java.io.IOException;
import java.util.HashMap;
import spark.Request;
import spark.Response;
import spark.Route;

public class getSongNames extends genericHandler implements Route {

  public String[] songNames;
  public getSongNames() {
    this.songNames = new String[]{"(everything i do) i do it for you",
        "(i can't get no) satisfaction",
        "(i know) i'm losing you", "(i've been) searchin' so long",
        "(it's just) the way that you love me",
        "(just like) starting over", "(keep feeling) fascination",
        "(marie's the name) his latest flame",
        "(now and then there's) a fool such as i", "(oh) pretty woman",
        "(shake, shake, shake) shake your booty",
        "(she's) sexy + 17", "(sittin' on) the dock of the bay", "(theme from) valley of the dolls",
        "(they long to be) close to you",
        "(when you gonna) give it up to me", "(you gotta) fight for your right",
        "(you're the) devil in disguise",
        "(your love has lifted me) higher and higher",
        "(your love keeps lifting me) higher and higher",
        "...baby one more time", "1, 2 step", "19 somethin'", "1979", "19th nervous breakdown",
        "2 become 1",
        "21 guns", "21 questions", "22", "25 or 6 to 4", "3", "3 a.m. eternal", "4 minutes",
        "4 seasons of loneliness",
        "5 o'clock", "50 ways to leave your lover", "50 ways to say goodbye", "634-5789",
        "7 things",
        "9 to 5",
        "a big hunk o' love", "a blossom fell", "a boy named sue", "a cowboy's work is never done",
        "a different corner",
        "a groovy kind of love", "a guy is a guy", "a hard day's night", "a little in love",
        "a love bizarre", "a love song",
        "a moment like this", "a new day has come", "a rockin' good way", "a rose is still a rose",
        "a sky full of stars", "a song for mama", "a summer song", "a thousand miles",
        "a thousand years",
        "a whiter shade of pale", "a whole new world", "a woman's worth", "abc", "abracadabra",
        "according to you", "addicted to love", "adia", "adore you", "affair of the heart",
        "after all",
        "after the love has gone", "after the lovin'", "again", "against all odds", "ahab the arab",
        "ain't no mountain high enough", "ain't no sunshine", "ain't no woman",
        "ain't nothing like the real thing", "ain't that a shame", "ain't too proud to beg",
        "ain't it funny", "ain't no other man", "alejandro", "alfie", "alive and kicking",
        "all about that bass", "all around the world", "all by myself",
        "all day and all of the night",
        "all falls down", "all for love", "all i have", "all i have to give",
        "all i really want to do",
        "all i wanna do", "all i wanna do is make love to you", "all my love", "all of me",
        "all of the lights", "all out of love", "all she wants to do is dance", "all shook up",
        "all summer long", "all that she wants", "all the man that i need", "all the right moves",
        "all the small things", "all those years ago", "all through the night",
        "all you need is love",
        "all the way", "allegheny moon", "allentown", "almost doesn't count", "alone",
        "along came jones", "already gone", "always", "always be my baby", "always in my heart",
        "always on my mind", "am i wrong", "amanda", "amazing", "amazing grace", "america",
        "american honey", "american kids", "american pie", "american soldier", "amnesia",
        "among my souvenirs", "an innocent man", "anaconda", "angel", "angie", "angie baby",
        "animals",
        "annie's song", "another day in paradise", "another sad love song",
        "another saturday night",
        "answer me my love", "anticipation", "any day now", "anyone who had a heart",
        "anything for you", "anytime you need a friend", "apologize", "applause", "april love",
        "are you gonna kiss me or not", "are you lonesome tonight", "armageddon it",
        "as good as i once was", "as i lay me down", "as long as you love me", "at seventeen",
        "at your best", "austin", "ayo technology", "babe", "baby", "baby boy", "baby don't go",
        "baby got back", "baby hold on", "baby i love you", "baby i need your loving",
        "baby it's you",
        "baby workout", "back 2 good", "back at one", "back for good", "back on the chain gang",
        "back stabbers", "back to december", "back and forth", "bad", "bad bad leroy brown",
        "bad blood", "bad boy", "bad boys", "bad medicine", "bad moon rising", "bad romance",
        "bad time", "bag lady", "bailamos", "bailando", "ball of confusion",
        "ballad of a teenage queen", "ballerina girl", "band on the run", "bang a gong",
        "bang bang",
        "barbara ann", "barefoot blue jean night", "barracuda", "bartender", "battlefield",
        "be like that", "be my baby", "be with you", "beachin'", "beat it", "beautiful girls",
        "beautiful liar", "beautiful life", "beautiful soul", "beauty and a beat",
        "beauty is only skin deep", "because i love you", "because of love", "because of you",
        "because you loved me", "bed of roses", "been around the world", "beep",
        "beer for my horses",
        "before he cheats", "behind these hazel eyes", "being with you", "believe", "ben",
        "bennie and the jets", "bent", "bernadette", "bernardine", "berzerk", "best friend",
        "best of you", "best song ever", "best thing i never had", "bette davis eyes",
        "better be good to me", "better in time", "better off alone", "better than me",
        "beverly hills",
        "beyond the sea", "big girls don't cry", "big green tractor", "big love", "big pimpin'",
        "big time", "billie jean", "billionaire", "bills, bills, bills", "birthday",
        "birthday cake",
        "birthday sex", "bitter sweet symphony", "black cat", "black or white", "black velvet",
        "blah blah blah", "blame it on the bossa nova", "blank space", "bleeding love", "bless you",
        "blow", "blowin' in the wind", "blowing kisses in the wind", "blown away", "blue bayou",
        "blue eyes", "blue monday", "blue suede shoes", "blueberry hill", "blurred lines",
        "body party",
        "boogie on reggae woman", "boogie wonderland", "boom boom pow", "boom clap", "bootylicious",
        "bop gun", "borderline", "born in the usa", "born this way", "born to be my baby",
        "born to be wild", "bossa nova baby", "botch-a-me", "bottoms up",
        "boulevard of broken dreams",
        "boy from new york city", "boyfriend", "boys 'round here", "brass in pocket", "break free",
        "break it off", "break it to me gently", "breakaway",
        "breakin' in a brand new broken heart",
        "breakin' my heart", "breaking the habit", "breathe", "breathe again", "breathless",
        "bridge over troubled water", "brilliant disguise", "bring me to life", "broken hearted me",
        "broken-hearted melody", "brokenhearted", "brown eyed girl", "brown sugar", "bubbly",
        "budapest", "buffalo stance", "building a mystery", "bump n' grind", "bungle in the jungle",
        "burn", "burn it down", "burnin' it down", "burning love", "bus stop", "busted",
        "butterflies",
        "buttons", "buy u a drank", "c'est si bon", "california girls", "california gurls",
        "california nights", "call me", "call me maybe", "call on me", "call me when you're sober",
        "calling all angels", "can i get a...", "can we talk", "can you feel the love tonight",
        "can you find it in your heart", "can't believe it", "can't buy me love",
        "can't feel my face",
        "can't fight this feeling", "can't fight the moonlight", "can't get enough of your love",
        "can't get it out of my head", "can't get you out of my head", "can't help falling in love",
        "can't hold us down", "can't let go", "can't nobody hold me down",
        "can't smile without you",
        "can't stay away from you", "can't stop lovin' you", "can't stop this thing we started",
        "can't we try", "candle in the wind", "candy shop", "car wash", "caribbean queen",
        "carnival",
        "carrie ann", "carry on wayward son", "carry out", "cars", "cat's in the cradle",
        "catch my breath", "cater 2 u", "causing a commotion", "celebration", "centuries",
        "chain gang",
        "chances are", "chandelier", "change clothes", "change of heart", "change the world",
        "changing partners", "chantilly lace", "chariot", "charlie brown", "check yo self",
        "check on it", "cheers", "cherish", "cherry, cherry", "chicken fried", "china girl",
        "chuck e's in love", "church of the poison mind", "circus", "clean up woman",
        "cleanin' out my closet", "clocks", "close my eyes forever", "close to you", "closer",
        "club can't handle me", "clumsy", "coco jamboo", "cold as ice", "cold hearted",
        "cold rock a party", "cold sweat", "cold, cold heart", "colder weather",
        "come a little bit closer", "come back to me", "come dancing", "come on over baby",
        "come on-a my house", "come over", "come sail away", "come together", "come with me",
        "comin' in and out of your life", "coming on strong", "coming out of the dark", "coming up",
        "complicated", "conga", "contagious", "control", "cool", "cool for the summer",
        "cool it now",
        "copacabana", "could it be magic", "couldn't get it right", "count me in", "count on me",
        "counting stars", "cover girl", "cover me", "coward of the county", "cowboy take me away",
        "cradle of love", "crash and burn", "crash my party", "crazy", "crazy for you",
        "crazy girl",
        "crazy in love", "crocodile rock", "cross over the bridge", "cruel summer", "cruisin'",
        "cry for help", "cry me a river", "cryin'", "crying", "crying in the chapel", "crying time",
        "cups", "da ya think i'm sexy", "damn i wish i was your lover", "dance hall days",
        "dance the night away", "dance to the music", "dance with me", "dance, dance",
        "dancing in the dark", "dancing machine", "dancing on the ceiling", "dancing queen",
        "danger zone", "dani california", "daniel", "danny's song", "dark horse", "dark lady",
        "day 'n' nite", "day dreaming", "daydream", "daydream believer", "daylight",
        "days of wine and roses", "dear future husband", "dear hearts and gentle people",
        "dedicated to the one i love", "deeper and deeper", "deja vu", "delta dawn", "denise",
        "devil inside", "devil woman", "diamonds", "diary",
        "did you ever have to make up your mind?",
        "didn't we almost have it all", "die young", "dip it low", "dirt off your shoulder",
        "dirt road anthem", "dirty diana", "dirty laundry", "dirty little secret", "disappear",
        "disco inferno", "disturbia", "diva", "dizzy", "do i do", "do i have to say the words?",
        "do i make you proud", "do wah diddy diddy", "do what u want", "do you believe in magic",
        "do you know the way to san jose", "do you really want to hurt me", "do you remember",
        "do you want to know a secret", "doctor my eyes", "domino", "don't", "don't be cruel",
        "don't break the heart that loves you", "don't bring me down", "don't cha",
        "don't cry for me argentina", "don't do me like that", "don't fall in love with a dreamer",
        "don't forbid me", "don't forget about us", "don't get me wrong",
        "don't go breaking my heart",
        "don't happen twice", "don't know much", "don't know why", "don't leave me this way",
        "don't let it end", "don't let the stars get in your eyes",
        "don't let the sun go down on me",
        "don't lie", "don't look back", "don't lose my number", "don't mean nothing",
        "don't mess with my man", "don't phunk with my heart", "don't rush me",
        "don't stand so close to me", "don't stop", "don't stop 'til you get enough",
        "don't stop believin'", "don't stop the music", "don't take the girl",
        "don't talk to strangers", "don't tell 'em", "don't tell me", "don't turn around",
        "don't wanna go home", "don't wanna lose you", "don't worry baby", "don't worry, be happy",
        "don't you", "don't you know what the night can do", "don't you want me",
        "don't you worry 'bout a thing", "double vision", "down", "down low", "down on me",
        "down under", "downtown", "downtown train", "drag me down", "dream baby", "dream lover",
        "dream on", "dreamlover", "dreams", "dress you up", "drift away", "drive", "drive by",
        "drivin' my life away", "drop it like it's hot", "drop it like it's hot",
        "drops of jupiter",
        "drunk in love", "drunk on a plane", "drunk on you", "dude", "dum dum", "dust in the wind",
        "e.t.", "earned it", "ebony and ivory", "edge of seventeen", "eenie meenie",
        "eight days a week", "elastic heart", "electric blue", "elvira", "emotional rescue",
        "emotions",
        "empire state of mind", "empty garden", "end of the road", "endless love",
        "endless summer nights", "enjoy the silence", "epic", "eres tu", "escapade", "escape",
        "eternal flame", "even if it breaks your heart", "even the nights are better",
        "every 1's a winner", "every breath you take", "every kinda people", "every little step",
        "every little thing she does is magic", "every rose has its thorn",
        "every woman in the world",
        "everybody", "everybody have fun tonight", "everybody loves me but you",
        "everybody loves somebody", "everybody plays the fool", "everybody's somebody's fool",
        "everyday", "everyday is a winding road", "everyday people", "everything",
        "everything is beautiful", "everytime", "everytime you go away", "evil woman",
        "excuse me miss",
        "exhale", "express yourself", "eye in the sky", "eyes without a face", "f**k you",
        "fading like a flower", "faith", "faithful", "faithfully", "fall in love with me",
        "fallin'",
        "fallin' for you", "fanny", "fantasy", "far away", "fast car", "fastlove", "father figure",
        "feel good inc", "feel like makin' love", "feel so close", "feelin' stronger every day",
        "feels like the first time", "feels so right", "fergalicious", "fever", "fiesta",
        "fight song",
        "fighter", "finally", "fire and rain", "fire burning", "firework", "first time",
        "flashing lights", "fly away", "fly like an eagle", "fly over states", "follow me", "fool",
        "fooled around and fell in love", "foolish little girl", "footloose", "for all we know",
        "for the love of money", "for what it's worth", "for your eyes only", "for your love",
        "forever", "forever and for always", "forever your girl", "found out about you",
        "four walls",
        "frankie", "freddie's dead", "free fallin'", "free ride", "freedom 90", "freeway of love",
        "fresh", "friendly persuasion", "from the bottom of my broken heart", "from this moment on",
        "frozen", "full moon", "funky broadway", "funkytown", "g.d.f.r.", "games people play",
        "genie in a bottle", "georgia on my mind", "georgy girl", "get back", "get busy",
        "get down on it", "get down tonight", "get lucky", "get off",
        "get outta my dreams, get into my car", "get ready", "get right", "get up", "getaway",
        "gettin' jiggy wit it", "ghost", "gimme little sign", "gimme the light", "gin and juice",
        "girl crush", "girl on fire", "girl, you'll be a woman soon", "girlfriend",
        "girls just want to have fun", "gitarzan", "give a little bit", "give it to me",
        "give me love",
        "give me one reason", "give me the night", "give your heart a break", "gives you hell",
        "giving it up for your love", "giving you the benefit", "giving you the best that i got",
        "glamorous", "glendora", "glory days", "go home", "go the distance", "go your own way",
        "god gave me you", "god must have spent a little more time on you", "gold", "gold digger",
        "golden years", "goldfinger", "gone till november", "good enough", "good feeling",
        "good for you", "good girl", "good life", "good luck charm", "good morning beautiful",
        "good thing", "goodbye yellow brick road", "goodies", "goodnight tonight",
        "goody two shoes",
        "got my mind set on you", "got to be real", "got to get you into my life", "gotham city",
        "gotta be somebody", "gotta get thru this", "great balls of fire", "greatest love of all",
        "green light", "green river", "grenade", "grown men don't cry",
        "guess things happen that way",
        "guilty", "habits", "hair", "half as much", "half breed", "halo", "hands clean",
        "handy man",
        "hangin' tough", "hanging by a moment", "happy people", "hard", "hard habit to break",
        "hard knock life", "hard to love", "hard to say i'm sorry", "harlem shake", "hate me",
        "hate that i love you", "hats off to larry", "have i told you lately",
        "have you ever really loved a woman?", "have you ever?", "haven't met you yet",
        "having a party", "hazard", "hazy shade of winter", "he ain't heavy, he's my brother",
        "he can't love u", "he wasn't man enough", "he'll have to go", "heart attack",
        "heart full of soul", "heart of glass", "heart of gold", "heart to heart", "heartbeat song",
        "heartbreak hotel", "heartbreaker", "heartless", "heat of the night",
        "heaven is a place on earth", "helen wheels", "hello", "hello again", "hello, dolly!",
        "hello, i love you", "hello, it's me", "help me", "help me, rhonda", "help!",
        "here and now",
        "here comes the rain again", "here comes the sun", "here i am", "here i go again",
        "here we are", "here we go again", "here without you", "here you come again", "hero",
        "hey jealous lover", "hey jealousy", "hey jude", "hey mama", "hey there", "hey ya!",
        "hey, soul sister", "higher ground", "higher love", "hit 'em up style", "hit me off",
        "hit the road jack", "hold it against me", "hold me", "hold on to the nights",
        "hold your head up", "holding back the years", "hole hearted", "holiday", "hollaback girl",
        "hollywood swinging", "holy grail", "homeward bound", "honey", "honey bee",
        "honey, i'm good.",
        "honky tonk women", "hook", "hoop-dee-doo", "hooray for hazel", "hot blooded",
        "hot diggity",
        "hot fun in the summertime", "hot girls in love", "hot in the city", "hot n cold",
        "hot rod lincoln", "hot n cold", "hound dog", "how am i supposed to live without you",
        "how can we be lovers", "how can you mend a broken heart", "how deep is your love",
        "how do i live", "how do i make you", "how do you like me now?!", "how do you sleep?",
        "how forever feels", "how low", "how sweet it is", "how will i know",
        "how you gonna act like that", "how you gonna see me now", "how you remind me", "human",
        "human nature", "humpin' around", "hung up", "hungry heart", "hurt so bad",
        "hurting each other", "i ain't gonna stand for it", "i almost lost my mind", "i am a rock",
        "i believe i can fly", "i believe in you and me", "i can", "i can help",
        "i can see clearly now", "i can't get next to you", "i can't help myself",
        "i can't make you love me", "i can't sleep baby", "i can't stand it",
        "i can't stop loving you",
        "i cry", "i didn't mean to turn you on", "i dig rock and roll music", "i do not hook up",
        "i do!!", "i don't dance", "i don't know how to love him", "i don't need you",
        "i don't wanna",
        "i don't wanna cry", "i don't wanna fight", "i don't wanna go on with you like that",
        "i don't wanna know", "i don't wanna live without your love",
        "i don't want this night to end",
        "i don't want to be", "i don't want to live without you", "i don't want to miss a thing",
        "i fall to pieces", "i finally found someone", "i found someone", "i get weak", "i go back",
        "i go to extremes", "i got stung", "i got the feelin'", "i got you babe", "i gotta feeling",
        "i guess that's why they call it the blues", "i hate this part", "i have nothing",
        "i heard a rumour", "i heard it through the grapevine", "i hope you dance",
        "i just called to say i love you", "i just can't help believing",
        "i just can't stop loving you", "i just fall in love again", "i just wanna love u",
        "i just wanna stop", "i just want to celebrate", "i kissed a girl", "i knew i loved you",
        "i knew you were trouble", "i knew you were waiting", "i like it", "i love a rainy night",
        "i love it", "i love music", "i love rock n' roll", "i love your smile",
        "i made it through the rain", "i need to know", "i need you", "i need your love",
        "i need your love tonight", "i never cry", "i never loved a man", "i run to you",
        "i saw her standing there", "i saw the light", "i say a little prayer", "i still believe",
        "i turn to you", "i walk the line", "i wanna be around", "i wanna be down",
        "i wanna dance with somebody", "i wanna get next to you", "i wanna go", "i want her",
        "i want it that way", "i want to be wanted", "i want to hold your hand",
        "i want to know what love is", "i want to take you higher", "i want to walk you home",
        "i want you", "i want you back", "i want you to want me",
        "i want you, i need you, i love you",
        "i want your sex", "i was made for lovin' you", "i was made to love her",
        "i went to your wedding", "i will always love you", "i will remember you", "i wish",
        "i wish it would rain", "i wish it would rain down", "i won't give up", "i write the songs",
        "i'd do anything for love", "i'll always love you", "i'll be", "i'll be doggone",
        "i'll be home", "i'll be loving you", "i'll be missing you", "i'll be there",
        "i'll be there for you", "i'll be your shelter", "i'll give all my love to you",
        "i'll have to say i love you in a song", "i'll make love to you",
        "i'll never fall in love again", "i'll never find another you",
        "i'll never love this way again", "i'll remember", "i'll stand by you", "i'll tumble 4 ya",
        "i'm a believer", "i'm coming out", "i'm every woman", "i'm gonna be alright",
        "i'm gonna love you just a little more", "i'm gonna make you love me",
        "i'm gonna make you mine", "i'm in love again", "i'm like a bird", "i'm n luv",
        "i'm not in love", "i'm not the only one", "i'm on fire", "i'm ready", "i'm real",
        "i'm so lonesome i could cry", "i'm sorry", "i'm sprung", "i'm still in love with you",
        "i'm still standing", "i'm still in love with you", "i'm too sexy", "i'm walkin'",
        "i'm with you", "i'm your angel", "i'm your baby tonight", "i'm your boogie man",
        "i'm yours",
        "i've got a rock 'n' roll heart", "i've gotta get a message to you", "if",
        "if ever you're in my arms again", "if everyone cared", "if i ain't got you",
        "if i could turn back time", "if i give my heart to you", "if i had a hammer",
        "if i were a boy", "if i were a carpenter", "if it isn't love", "if it makes you happy",
        "if today was your last day", "if u seek amy", "if wishes came true", "if you asked me to",
        "if you could read my mind", "if you had my love", "if you leave", "if you leave me now",
        "if you really love me", "if you want me to stay", "if you're gone",
        "if you're not the one",
        "if your girl only knew", "ignition", "imaginary lover", "imma be", "impulsive",
        "in america",
        "in da club", "in dreams", "in love with a girl", "in my head", "in the ayer",
        "in the closet",
        "in the ghetto", "in the rain", "in the still of the nite", "in your room", "in the end",
        "in the middle of an island", "incomplete", "independent women part i", "indian lake",
        "indian outlaw", "infatuation", "informer", "insane in the brain", "insensitive",
        "inside your heaven", "instant karma", "invisible man", "ironic", "irreplaceable",
        "is this love", "island girl", "islands in the stream", "it ain't over 'til it's over",
        "it ends tonight", "it goes like this", "it must be him", "it must have been love",
        "it never rains in southern california", "it was a good day", "it was almost like a song",
        "it wasn't me", "it will rain", "it's not my time", "it's a great day to be alive",
        "it's a heartache", "it's a mistake", "it's all coming back to me now", "it's been awhile",
        "it's five o'clock somewhere", "it's gonna work out fine", "it's impossible",
        "it's like that",
        "it's my life", "it's my party", "it's my turn", "it's not for me to say",
        "it's not right but it's okay", "it's over", "it's so easy",
        "it's so hard to say goodbye to yesterday", "it's still rock and roll to me",
        "it's the same old song", "it's too soon to know", "it's your love", "it's your thing",
        "izzo",
        "jaded", "jailhouse rock", "jamaica farewell", "janie's got a gun", "jar of hearts",
        "jealousy",
        "jenny jenny", "jenny from the block", "jessie's girl", "jesus walks",
        "jesus, take the wheel",
        "jet", "jet airliner", "jive talkin'", "joanna", "johnny b goode", "joyride",
        "judy's turn to cry", "juke box baby", "jumpin' jack flash", "jungle boogie",
        "just a friend",
        "just a girl", "just a kiss", "just a lil bit", "just between you and me",
        "just can't get enough", "just dance", "just like jesse james", "just lose it",
        "just my imagination", "just the way you are", "just to see her", "justified and ancient",
        "justify my love", "karma", "karma chameleon", "keep coming back", "keep holding on",
        "keep it comin'", "keep it comin' love", "keep on loving you", "keep on walkin'",
        "keep on, keepin' on", "keep searchin'", "keep the fire burnin'", "keep a knockin'",
        "kewpie doll", "key west intermezzo", "kick the dust up", "killing me softly with his song",
        "king of wishful thinking", "kiss me", "kiss you all over", "kissing a fool", "knee deep",
        "knock on wood", "knock you down", "knowing me, knowing you", "kodachrome", "kokomo",
        "kryptonite", "kung fu fighting", "la bamba", "la isla bonita", "lady madonna", "landslide",
        "last friday night", "last kiss", "last train to clarksville", "lawyers in love",
        "lay down sally", "lay lady lay", "lay me down", "lay your hands on me", "layla",
        "leader of the band", "lean on", "lean on me", "learnin' the blues", "leather and lace",
        "leavin'", "legs", "lesson in leavin'", "let 'em in", "let it be", "let it whip",
        "let me go",
        "let my love open the door", "let the four winds blow", "let the music play",
        "let your love flow", "let's dance", "let's get it on", "let's get it started",
        "let's get married", "let's get rocked", "let's go", "let's groove", "let's stay together",
        "let's wait awhile", "letters from home", "life is a highway", "life is a highway",
        "light my fire", "lighters", "lightnin' strikes", "lights", "like a boy", "like a prayer",
        "like a rolling stone", "like a stone", "like a virgin", "like glue", "like i love you",
        "like i'm gonna lose you", "like you'll never see me again", "linger", "lips are movin",
        "lips of an angel", "lips of an angel", "lipstick on your collar",
        "listen to what the man said", "little jeannie", "little lies", "little red rooster",
        "little sister", "little talks", "little town flirt", "live and let die",
        "live like you were dying", "live to tell", "livin' on a prayer", "livin' on the edge",
        "livin' thing", "living for the city", "living in america", "living inside myself",
        "living and living well", "locked out of heaven", "lola", "london bridge", "lonely boy",
        "lonely days", "lonely ol' night", "lonely teardrops", "long cool woman", "long tall sally",
        "long time gone", "longer", "look away", "look what you done for me",
        "looking for a new love",
        "looking through your eyes", "looks like we made it", "lose my breath", "lose yourself",
        "losing you", "lost in love", "lost without u", "love bites", "love don't cost a thing",
        "love hangover", "love her madly", "love hurts", "love in an elevator",
        "love in the first degree", "love is a wonderful thing", "love is all around",
        "love letters in the sand", "love like this", "love lockdown", "love me do",
        "love me harder",
        "love me like you do", "love me tender", "love never felt so good", "love of my life",
        "love on the rocks", "love runs out", "love shack", "love sneakin' up on you",
        "love so right",
        "love somebody", "love story", "love takes time", "love the way you lie", "love touch",
        "love train", "love will conquer all", "love will lead you back", "love will never do",
        "love will turn you around", "love you inside out", "lovegame", "lover girl",
        "lover, lover",
        "loverboy", "loves me like a rock", "lovestoned", "loving you", "low", "lucille",
        "lucky star",
        "lucy in the sky with diamonds", "luka", "lullaby", "mack the knife", "mad",
        "mad about you",
        "magic carpet ride", "magic stick", "make it happen", "make me smile", "make you sweat",
        "makes me wonder", "making love", "making love out of nothing at all", "mama",
        "mama can't buy you love", "mama from the train", "mama said", "mama's broken heart",
        "mama's pearl", "man in the mirror", "man! i feel like a woman!", "mandy", "manic monday",
        "maps", "margaritaville", "marvin gaye", "mary jane's last dance", "master blaster",
        "masterpiece", "material girl", "me and bobby mcgee", "me and mrs. jones",
        "me and my broken heart", "mean woman blues", "meant to live", "meet me half way",
        "meet me halfway", "meet virginia", "memories are made of this", "mercedes boy",
        "mercy mercy me", "message to michael", "miami", "mickey", "midnight at the oasis",
        "midnight blue", "mine", "mirror mirror", "mirrors", "misery", "misled", "miss independent",
        "miss me blind", "miss you", "miss you much", "missing", "missing you", "missing you now",
        "mississippi girl", "misty", "mockin' bird hill", "mockingbird", "modern girl",
        "moment 4 life",
        "mona lisa", "money", "money for nothing", "money honey", "money maker", "monkey",
        "mony mony",
        "moody river", "moon river", "more and more", "more love", "more than words",
        "more than a woman", "morning train", "mother and child reunion", "mother popcorn",
        "motivation", "motorcycle mama", "motownphilly", "move along", "move bitch",
        "moves like jagger", "mr wonderful", "mr. bojangles", "mr. roboto", "mr. tambourine man",
        "mr. vain", "mrs. robinson", "ms. jackson", "my all", "my band", "my best friend",
        "my blue heaven", "my cherie amour", "my chick bad", "my ding-a-ling", "my girl",
        "my happiness", "my happy ending", "my heart belongs to me", "my heart can't tell you no",
        "my heart has a mind of its own", "my heart will go on", "my humps", "my immortal",
        "my life would suck without you", "my list", "my love", "my love is your love",
        "my prerogative", "my whole world ended", "my wish came true", "naked eye", "nasty",
        "naturally", "naughty girl", "need you now", "need you tonight", "neither one of us",
        "never",
        "never again", "never gonna give you up", "never had a dream come true",
        "never leave you - uh ooh, uh oooh!", "never my love", "never tear us apart",
        "never, never gonna give you up", "new divide", "new sensation", "night", "night changes",
        "night fever", "night lights", "nikita", "no air", "no more \"i love you's\"",
        "no more lonely nights", "no more tears", "no one", "no other love",
        "no shoes, no shirt, no problems", "no time", "no, no, no", "nobody",
        "nobody does it better",
        "nobody told me", "not a bad thing", "not afraid", "not over you", "not tonight",
        "nothin' but a good time", "nothing compares 2 u", "nothing's gonna stop us now",
        "november rain", "now and forever", "nowhere man", "numb", "number one spot", "obsessed",
        "ode to billie joe", "off the wall", "oh", "oh girl", "oh, pretty woman", "old cape cod",
        "on a carousel", "on bended knee", "on broadway", "on our own", "on the floor",
        "one fine day",
        "one last cry", "one last time", "one mint julep", "one moment in time", "one more night",
        "one more try", "one night", "one night in bangkok", "one of us", "one step at a time",
        "one sweet day", "one thing", "one time", "one week", "only", "only girl",
        "only god knows why",
        "only time", "only women bleed", "only yesterday", "ooh baby baby",
        "oops!... i did it again",
        "open arms", "open your heart", "opposites attract", "ordinary people", "otherside",
        "our lips are sealed", "our song", "outta control", "overkill", "owner of a lonely heart",
        "p.i.m.p.", "papa don't preach", "papa loves mambo", "papa was a rolling stone",
        "papa's got a brand new bag", "paparazzi", "paperback writer", "paradise", "paradise city",
        "paralyzer", "part of me", "part-time lover", "partition", "party in the u.s.a.",
        "party rock anthem", "party up", "party in the u.s.a.", "passion", "patience", "payphone",
        "peaceful", "peggy sue", "penny lane", "penny lover", "people", "people are crazy",
        "perfect way", "personally", "philadelphia freedom", "photograph", "picture",
        "pictures of matchstick men", "piece of me", "pimpin' all over the world", "pink houses",
        "place in this world", "play it again", "pleasant valley sunday", "please forgive me",
        "please mr. postman", "please please me", "please remember me", "pocketful of sunshine",
        "poison ivy", "poker face", "polk salad annie", "pon de replay", "pontoon",
        "pound the alarm",
        "pour it up", "pour some sugar on me", "power trip", "praying for time", "pretend",
        "pretty blue eyes", "pretty girl rock", "price tag", "pride and joy", "private dancer",
        "problem", "promiscuous", "promise", "promises", "proud mary", "prove your love",
        "psychedelic shack", "puff", "pump it", "pumped up kicks",
        "put a little love in your heart",
        "put your hands together", "queen of the hop", "quit playing games", "radar love",
        "rags to riches", "rain", "raindrops keep fallin' on my head", "rainy day women #12 and 35",
        "rainy days and mondays", "ramblin' man", "ramblin' rose", "rapture", "rather be",
        "ray of light", "reach out i'll be there", "real good man", "realize", "reason to believe",
        "rebirth of slick", "red dirt road", "red red wine", "red solo cup", "redneck woman",
        "refugee",
        "rehab", "release me", "remember the time", "remember when", "remember you're mine",
        "renegade",
        "replay", "respect", "return to innocence", "return to me", "revolution", "rhiannon",
        "rhythm is gonna get you", "rhythm nation", "rhythm of my heart", "rich girl",
        "riders on the storm", "ridin' solo", "right here waiting", "right place, wrong time",
        "right round", "ring my bell", "ring of fire", "roar", "rock 'n' roll fantasy",
        "rock and roll all nite", "rock and roll dreams come through", "rock and roll music",
        "rock me tonite", "rock that body", "rock the boat", "rock wit'cha", "rock with you",
        "rock your body", "rock and roll music", "rock the boat", "rocket man", "rockin' robin",
        "rockstar", "rocky mountain high", "roll out", "roll with it", "romeo's tune", "roni",
        "roses",
        "round and round", "roundabout", "royals", "ruby tuesday",
        "ruby, don't take your love to town",
        "rude boy", "run away child, running wild", "run to you", "run-around", "runaway",
        "runaway love", "runnin' outta moonlight", "running on empty", "running scared",
        "running with the night", "rush rush", "s&m", "sos", "sad songs",
        "said i loved you...but i lied", "same girl", "same old lang syne", "sara", "satisfied",
        "satisfy you", "saturday in the park", "saturday night", "save your heart for me",
        "savin' me",
        "saving all my love for you", "saving forever for you", "say it right", "say my name",
        "say say say", "say something", "say yes", "say you love me", "say you will",
        "say you'll be there", "say you're mine again", "say you, say me", "scar tissue", "scars",
        "school day", "school's out", "searchin'", "secret", "secret garden", "secret love",
        "secret lovers", "secrets", "send for me", "send one your love", "sensual seduction",
        "separate lives", "separate ways", "september", "september morn", "serpentine fire",
        "seven year ache", "sexual healing", "sexy and i know it", "sexy chick", "sexy love",
        "sexyback", "shadow of the day", "shake", "shake it off", "shake that",
        "shake, rattle and roll", "shapes of things", "shattered dreams", "she believes in me",
        "she bop", "she cried", "she drives me crazy", "she knows", "she looks so perfect",
        "she loves you", "she wants to dance with me", "she will be loved", "she will be loved",
        "she's a beauty", "she's a fool", "she's got you", "she's just my style",
        "she's out of my life", "sheila", "shine a little love", "ships", "short people",
        "should've known better", "show me", "show me the meaning of being lonely",
        "show me the way",
        "shut down", "shut up and drive", "shy guy", "sideshow", "silly love songs",
        "simply irresistible", "since u been gone", "sing", "sing a song", "sing for the moment",
        "single ladies", "sink the bismark", "sir duke", "sittin' up in my room", "sk8er boi",
        "sky pilot", "sledgehammer", "sleeping bag", "slip slidin' away", "sloop john b",
        "small town",
        "smells like teen spirit", "smoke on the water", "smoky mountain rain", "smooth criminal",
        "snap your fingers", "snow", "snowbird", "so emotional", "so fresh, so clean",
        "so in to you",
        "so sick", "soak up the sun", "society's child", "soldier", "soldier boy",
        "some kind of wonderful", "somebody that i used to know", "somebody to love",
        "somebody's baby",
        "someday", "someone saved my life tonight", "somethin' 'bout a truck", "somethin' bad",
        "something", "something about you", "something happened on the way to heaven",
        "something to believe in", "something to talk about", "something's burning", "sometimes",
        "sometimes when we touch", "somewhere in the night", "somewhere out there",
        "song sung blue",
        "sorry seems to be the hardest word", "southern hospitality", "space oddity",
        "spanish harlem",
        "speak to the sky", "speed of sound", "speedy gonzales", "spice up your life",
        "spies like us",
        "spill the wine", "spirit in the sky", "splash waterfalls", "splish splash", "springsteen",
        "stand back", "stand by me", "stand tall", "stand up", "starships", "stay", "stay with me",
        "stayin' alive", "step by step", "step in the name of love", "stickwitu", "still the one",
        "still water", "stitches", "stop and stare", "story of my life", "straight from the heart",
        "straight up", "stranger in paradise", "strangers in the night", "stray cat strut",
        "streets of philadelphia", "strong enough", "stronger", "strut", "stuck like glue",
        "stuck on you", "style", "suddenly", "sugar", "sugar moon", "sugar walls",
        "sugar, we're goin' down", "sultans of swing", "summer", "summer in the city",
        "summer love",
        "summer of '69", "summertime sadness", "sundown", "sunny came home",
        "sunshine on my shoulders",
        "super bass", "superfly", "superman", "superstar", "superstition",
        "sure be cool if you did",
        "surfer girl", "surfin' safari", "surfin' u.s.a.", "surrender", "survivor", "suspicions",
        "suspicious minds", "sussudio", "swear it again", "sweat", "sweet baby", "sweet caroline",
        "sweet child o' mine", "sweet city woman", "sweet dreams", "sweet lady",
        "sweet little sixteen",
        "sweet love", "sweet nothin's", "sweet nothing", "sweet pea", "sweet talking woman",
        "sweetest girl", "switch", "true", "tainted love", "take a back road", "take a bow",
        "take a chance on me", "take a little ride", "take a picture", "take it away",
        "take it off",
        "take it on the run", "take me home", "take me home tonight", "take me home, country roads",
        "take me to church", "take on me", "take the long way home", "take the money and run",
        "take these chains from my heart", "take this heart", "take time to know her",
        "take you there",
        "takin' care of business", "talk dirty", "talk to me", "talking body", "tattoo", "taxi",
        "team",
        "teardrops on my guitar", "tears in heaven", "teddy bear", "teenage dream", "telephone",
        "telephone line", "tell her about it", "tell it like it is", "tell it to my heart",
        "temperature", "tennessee waltz", "thank god i found you", "thank god i'm a country boy",
        "thank the lord for the night time", "thank you", "that don't impress me much", "that girl",
        "that sunday, that summer", "that's all there is to that", "that's all you gotta do",
        "that's amore", "that's my kind of night", "that's that", "that's the way",
        "that's the way i've always heard it should be", "that's the way it is",
        "that's the way love goes", "that's the way love is", "that's the way of the world",
        "the a team", "the air that i breathe", "the battle of new orleans",
        "the beach boys medley",
        "the beat goes on", "the best day", "the best of times", "the best things in life are free",
        "the boy is mine", "the boys are back in town", "the boys of summer",
        "the city of new orleans",
        "the climb", "the closer i get to you", "the devil went down to georgia",
        "the door is still open to my heart", "the edge of glory", "the end of the innocence",
        "the finer things", "the first cut is the deepest", "the first time ever i saw your face",
        "the flame", "the gambler", "the girl from ipanema", "the girl is mine",
        "the glamorous life",
        "the good stuff", "the hanging tree", "the hardest thing", "the heart wants what it wants",
        "the hills", "the house that built me", "the joker", "the jump off", "the last time",
        "the lazy song", "the letter", "the loco-motion", "the logical song", "the longest time",
        "the look", "the love you save", "the lover in me", "the main event", "the man",
        "the mighty quinn", "the monster", "the morning after", "the motown song",
        "the mummers' dance",
        "the name of the game", "the night they drove old dixie down", "the one",
        "the one i gave my heart to", "the one that got away", "the one that you love",
        "the other side", "the power of love", "the promise of a new day",
        "the rain, the park and other things", "the real slim shady", "the remedy",
        "the river of dreams", "the safety dance", "the show goes on", "the sign",
        "the space between",
        "the streak", "the stroke", "the sweet escape", "the things we do for love",
        "the thrill is gone", "the tide is high", "the tijuana jail", "the way", "the way i are",
        "the way of love", "the way we were", "the way you do the things you do",
        "the way you love me",
        "the way you make me feel", "the way you move", "the whole world",
        "the winner takes it all",
        "then", "then came you", "there you'll be", "there'll be sad songs", "these dreams",
        "these words", "things", "think", "think i'm in love", "thinking out loud",
        "this ain't a love song", "this ain't a scene, it's an arms race", "this diamond ring",
        "this girl's in love with you", "this is it", "this kiss", "this love", "this magic moment",
        "this masquerade", "this ole house", "this one's for the children",
        "this used to be my playground", "thnks fr th mmrs", "thoia thoing",
        "those lazy hazy crazy days of summer", "thought i'd died and gone to heaven", "thriller",
        "through the years", "through the wire", "thunder island", "tik tok", "ticket to ride",
        "till the world ends", "time after time", "time in a bottle", "time passages",
        "time, love and tenderness", "tired of being alone", "tired of waiting for you", "titanium",
        "to be a lover", "to love somebody", "today was a fairytale", "together forever",
        "tom dooley",
        "tonight", "tonight i celebrate my love", "tonight's the night",
        "too busy thinking about my baby", "too funky", "too hot", "too many rivers", "too much",
        "too much heaven", "too much time on my hands", "too much, too little, too late", "too shy",
        "too young", "top of the world", "total eclipse of the heart", "touch me",
        "touch me in the morning", "touch my body", "toxic", "tragedy", "treasure", "trouble",
        "troublemaker", "true blue", "true colors", "truffle butter", "truly", "truly madly deeply",
        "trumpets", "try again", "tryin' to get the feeling again", "tubthumping", "turn me on",
        "turn off the light", "turn off the light", "turn the beat around", "turn to stone",
        "turn your love around", "tusk", "twilight zone", "twist and shout", "twisted",
        "twistin' the night away", "two faces have i", "two hearts", "two out of three ain't bad",
        "two steps behind", "typical male", "uhh ahh", "uma thurman", "umbrella",
        "un-break my heart",
        "under the bridge", "undercover of the night", "underneath it all", "underneath it all",
        "undo it", "unfaithful", "unskinny bop", "until it sleeps", "until you come back to me",
        "unwell", "unwritten", "upside down", "uptight", "uptown funk!", "uptown girl", "urgent",
        "use me", "use somebody", "use ta be my girl", "vacation", "valerie", "valley of tears",
        "venus", "victory", "vision of love", "viva la vida", "viva la vida", "vogue",
        "waiting for a girl like you", "waiting for tonight", "waiting on a friend",
        "wake me up when september ends", "waking up in vegas", "walk away", "walk away from love",
        "walk like an egyptian", "walk of life", "walk on by", "walk on water", "walk this way",
        "walking to new orleans", "wanksta", "wanna be startin' somethin'", "wannabe",
        "want to want me", "wanted", "wanted dead or alive", "watching the wheels",
        "water runs dry",
        "waterloo", "waves", "way down", "we are never ever getting back together", "we be burnin'",
        "we belong together", "we built this city", "we can work it out", "we can't stop",
        "we didn't start the fire", "we don't need another hero", "we don't talk anymore",
        "we found love", "we got a love thang", "we got the beat", "we r who we r", "we be burnin'",
        "we're all alone", "we're an american band", "we've got tonight", "we've only just begun",
        "weekend in new england", "welcome back", "welcome to the black parade",
        "welcome to the jungle", "west end girls", "what a diff'rence a day makes",
        "what a girl wants",
        "what about love", "what about us?", "what do you mean?", "what goes around comes around",
        "what have i done to deserve this?", "what have you done for me lately",
        "what hurts the most",
        "what i've done", "what is love", "what it takes", "what it's like", "what kind of fool",
        "what kind of man would i be?", "what makes you beautiful", "what the hell",
        "what the world needs now is love", "what was i thinkin'", "what will my mary say",
        "what you need", "what'd i say", "what's going on", "what's love got to do with it",
        "what's my name?", "what's on your mind", "what's your name", "whataya want from me",
        "whatcha say", "whatcha see is whatcha get", "whatever it is", "when a man loves a woman",
        "when a woman's fed up", "when i grow up", "when i think of you", "when i was your man",
        "when i'm back on my feet again", "when i'm gone", "when it's love", "when she cries",
        "when the going gets tough", "when will i be loved", "when will i see you again",
        "when you believe", "when you love a woman", "when you're mad", "when the sun goes down",
        "whenever i call you \"friend\"", "where do broken hearts go",
        "where does my heart beat now",
        "where have all the flowers gone", "where have you been", "where is the love",
        "where is the love?", "where the boys are", "where them girls at", "where were you",
        "where'd you go", "while you see a chance", "whistle", "white horse", "white rabbit",
        "who can it be now?", "who says", "who says you can't go home", "who's crying now",
        "who's johnny", "who's sorry now", "who's that girl", "who's zoomin' who",
        "whole lotta shakin' goin' on", "why baby why", "why can't this be love",
        "why can't we live together", "why do fools fall in love?", "why me", "why?", "wicked game",
        "wide awake", "wiggle", "wild night", "wild ones", "wild wild west", "wildest dreams",
        "will you be there", "will you still love me?", "wind it up", "windy", "wishin' and hopin'",
        "with a little luck", "with every beat of my heart", "without me", "without you", "woman",
        "woman in love", "womanizer", "wonder", "wonderful! wonderful!", "words get in the way",
        "work out", "working for the weekend", "would i lie to you?", "wrapped around your finger",
        "wrecking ball", "write this down", "written in the stars", "yakety yak", "year of the cat",
        "yellow submarine", "yesterday once more", "yesterday's songs", "you and i", "you and me",
        "you and me against the world", "you and tequila", "you are", "you are not alone",
        "you are the sunshine of my life", "you belong to me", "you belong with me",
        "you can depend on me", "you can't hurry love", "you da one", "you decorated my life",
        "you don't bring me flowers", "you don't have to say you love me",
        "you don't know how it feels", "you don't know me", "you don't know my name",
        "you don't mess around with jim", "you don't own me", "you give good love",
        "you give love a bad name", "you got it", "you got lucky", "you made me believe in magic",
        "you may be right", "you mean the world to me", "you must have been a beautiful baby",
        "you must love me", "you needed me", "you really got me", "you remind me of something",
        "you sang to me", "you send me", "you sexy thing", "you should be dancing",
        "you should be mine", "you shouldn't kiss me like this", "you won't see me", "you'll see",
        "you'll think of me", "you're all i need to get by", "you're beautiful",
        "you're gonna miss this", "you're in love", "you're in my heart", "you're just in love",
        "you're my everything", "you're my world", "you're no good", "you're so vain",
        "you're still the one", "you're the first, the last, my everything",
        "you're the inspiration",
        "you're the reason i'm living", "you've got a friend", "young at heart", "young blood",
        "young forever", "young turks", "your body's callin'", "your love",
        "your love is driving me crazy", "your love is my drug", "your precious love"};


  }

  @Override
  public Object handle(Request request, Response response) throws IOException {
      hashMap.clear();
      System.out.println(hashMap);

      try {
//        this.songInList = Arrays.stream(this.songNames).anyMatch(songsWanted::equals);
//        if (this.songInList) {
          hashMap.put("Song", this.songNames);
          hashMap.put("Result", "Success");
  } catch (Exception e) {
          return BadRequestSerialize(hashMap);
        }
    HashMap<String, Object> hashMapSuccessCopy = new HashMap(hashMap);
    return serialize(hashMapSuccessCopy);
  }

  public String[] getter(){
    return this.songNames;
  }

}
